import HomeRecipesList from "@/components/home/home-recipes-list";

export const metadata = {
    title: 'Recipes ',
    description: 'Generated by create next app',
}

export default function Home() {
    return <>
        <HomeRecipesList/>
    </>
}
